apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: jiang0613/gitops-demo
    newTag: b7a98f8efdc5581a59c6f45bc491a0c767f03142