apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: jiang0613/python-k8s  # 修改为与deployment.yaml中一致
    newTag: sha-1  # 只更新标签即可