name: 构建与部署

on:
  push:
    branches: [ master ,main]
    paths:
      - 'app.py'
      - 'Dockerfile'
      - 'requirements.txt'
# 添加这一部分来设置权限
permissions:
  contents: write

jobs:
  build-and-push:
    name: 构建并推送Docker镜像
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        # 确保检出时获取完整的git历史
        fetch-depth: 0

    - name: 登录DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 构建并推送
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/gitops-demo:latest,${{ secrets.DOCKER_USERNAME }}/gitops-demo:${{ github.sha }}

    - name: 验证镜像推送
      run: |
        echo "尝试查询推送的镜像"
        # 安装 skopeo 工具用于查询 Docker 镜像
        sudo apt-get update && sudo apt-get install -y skopeo
        # 查询镜像是否存在于 DockerHub
        skopeo inspect docker://${{ secrets.DOCKER_USERNAME }}/gitops-demo:latest || echo "镜像未找到"

    - name: 更新Kubernetes配置
      run: |
        # 生成一个短的提交SHA值
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        
        # 更新kustomization.yaml中的镜像标签
        sed -i "s|newTag: .*|newTag: sha-$SHORT_SHA|" ./k8s/kustomization.yaml
        
        # 更新镜像名称（如果需要从ghcr.io更改为DockerHub）
        sed -i "s|name: ghcr.io/jiangnuonnuo/gitops-demo|name: ${{ secrets.DOCKER_USERNAME }}/gitops-demo|" ./k8s/kustomization.yaml
        
        # 配置Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 提交更改
        git add ./k8s/kustomization.yaml
        git commit -m "更新应用到版本 sha-$SHORT_SHA"
        git push